### ISSUE TITLE
Your components look really good! Great job separating the files and preventing them from being too large

### ISSUE THREAD

**Issue by Elliehunt8** [The-Grim-Adventures-of-Billy-and-Mandy/fec#49]
https://github.com/The-Grim-Adventures-of-Billy-and-Mandy/fec/blob/3f5739a1708f6b7730b33a048172f7c835d74db3/fec-client/src/components/Overview/index.jsx#L34

**Comment by OwenMY** [comment]
Thank you for your feedback!
