### ISSUE TITLE
"A" is non descriptive 

### ISSUE THREAD

**Issue by Elliehunt8** [The-Grim-Adventures-of-Billy-and-Mandy/fec#50]
https://github.com/The-Grim-Adventures-of-Billy-and-Mandy/fec/blob/3f5739a1708f6b7730b33a048172f7c835d74db3/fec-client/src/components/Q%26A/AListEntry.jsx#L5

**Comment by OwenMY** [comment]
Styled components have been refractored with more descriptive names.
