### ISSUE TITLE
Use strings for your error catches so you know where the error is 

### ISSUE THREAD

**Issue by Elliehunt8** [The-Grim-Adventures-of-Billy-and-Mandy/fec#52]
https://github.com/The-Grim-Adventures-of-Billy-and-Mandy/fec/blob/3f5739a1708f6b7730b33a048172f7c835d74db3/fec-client/src/components/Q%26A/QA.jsx#L71

**Comment by OwenMY** [comment]
Strings have been placed to Identify errors.
