### ISSUE TITLE
Consider revising all your functions to the es6 arrow func format, otherwise this code looks really clean! Good job! 

### ISSUE THREAD

**Issue by Elliehunt8** [The-Grim-Adventures-of-Billy-and-Mandy/fec#53]
https://github.com/The-Grim-Adventures-of-Billy-and-Mandy/fec/blob/3f5739a1708f6b7730b33a048172f7c835d74db3/fec-client/src/components/Q%26A/QAListEntry.jsx#L33

**Comment by OwenMY** [comment]
Has been considered, we will continue to implement arrow functions from now on.
