### ISSUE TITLE
I noticed that you're not reusing some of the files in this folder, the mix of styled components in the files vs in this one file could be cleaned up

### ISSUE THREAD

**Issue by Elliehunt8** [The-Grim-Adventures-of-Billy-and-Mandy/fec#54]
https://github.com/The-Grim-Adventures-of-Billy-and-Mandy/fec/blob/3f5739a1708f6b7730b33a048172f7c835d74db3/fec-client/src/components/Q%26A/styles/Container.styles.js#L2

**Comment by OwenMY** [comment]
Folder has been deleted and styled components have been added into the component files themselves
