### ISSUE TITLE
Separate like this for readability 

### ISSUE THREAD

**Issue by Elliehunt8** [The-Grim-Adventures-of-Billy-and-Mandy/fec#61]
https://github.com/The-Grim-Adventures-of-Billy-and-Mandy/fec/blob/3f5739a1708f6b7730b33a048172f7c835d74db3/fec-client/src/components/Related/Card.jsx#L64

<div> 
  <Action Button 
    src
    onClick
  </Action Button> 
</div>

**Comment by es98dame** [comment]
fixed!
