### ISSUE TITLE
should use space between parenthesis such as } else { and if (), make sure you are all using the same linter. also missing else block content 

### ISSUE THREAD

**Issue by Elliehunt8** [The-Grim-Adventures-of-Billy-and-Mandy/fec#63]
https://github.com/The-Grim-Adventures-of-Billy-and-Mandy/fec/blob/3f5739a1708f6b7730b33a048172f7c835d74db3/fec-client/src/components/Related/OutfitList.jsx#L46

**Comment by es98dame** [comment]
I realized that my linter was not working. now it is working and all files that have linter errors were fixed
